# pytorch notebook

from [official website](https://pytorch.org/tutorials/) of pytorch

## Getting started





In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3) # torch tensor similar with numpy array
print(x)

tensor([[ 1.1750e-32,  4.8130e-38,  4.7224e-43],
        [ 0.0000e+00, -3.6906e+10,  4.5607e-41],
        [-3.6906e+10,  4.5607e-41,  1.2035e-38],
        [ 4.8533e-32,  1.5488e+04,  7.5203e-31],
        [ 4.8544e-32,  4.8125e-38,  2.7982e-36]])


In [3]:
x = torch.rand(5, 3) # random number array
print(x)

tensor([[0.9972, 0.4125, 0.9009],
        [0.7122, 0.1974, 0.1489],
        [0.6706, 0.5073, 0.2350],
        [0.9852, 0.5019, 0.8170],
        [0.3965, 0.8435, 0.4221]])


In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [5]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-2.2456,  1.1525,  0.7621],
        [-1.1239,  2.4926, -0.1461],
        [-1.1571, -1.2934, -1.2271],
        [-1.0064, -0.5615, -0.2114],
        [-0.2363,  1.1813,  0.9357]])


In [11]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.6505,  2.0032,  1.1016],
        [-0.8875,  3.4698,  0.2522],
        [-1.1027, -0.9055, -0.3426],
        [-0.3057, -0.4643,  0.6645],
        [ 0.2218,  1.6190,  1.8211]])


In [14]:
z = x + y

In [18]:
print(z)
z.size()

tensor([[-1.6505,  2.0032,  1.1016],
        [-0.8875,  3.4698,  0.2522],
        [-1.1027, -0.9055, -0.3426],
        [-0.3057, -0.4643,  0.6645],
        [ 0.2218,  1.6190,  1.8211]])


torch.Size([5, 3])

In [20]:
print(torch.add(x, y)) 

tensor([[-1.6505,  2.0032,  1.1016],
        [-0.8875,  3.4698,  0.2522],
        [-1.1027, -0.9055, -0.3426],
        [-0.3057, -0.4643,  0.6645],
        [ 0.2218,  1.6190,  1.8211]])


In [21]:
y.add_(x) # torch tensor can be added up by "+" or .add class function, using .add_ in-place addiction
print(y)  # if you using any class function with post-fix "_", it operate as in-place function which mean it will change original data.

tensor([[-1.6505,  2.0032,  1.1016],
        [-0.8875,  3.4698,  0.2522],
        [-1.1027, -0.9055, -0.3426],
        [-0.3057, -0.4643,  0.6645],
        [ 0.2218,  1.6190,  1.8211]])


In [25]:
print(x[:, 0])

tensor([-2.2456, -1.1239, -1.1571, -1.0064, -0.2363])


In [24]:
print(x[0, :])

tensor([-2.2456,  1.1525,  0.7621])


In [26]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [32]:
x

tensor([[-0.4509, -1.1769,  1.1374,  1.2477],
        [ 0.2567,  1.1684, -0.4885, -0.1104],
        [ 0.6069, -0.1305, -0.4458,  0.1145],
        [ 0.2869,  0.8131,  2.0107, -1.1139]])

In [33]:
x.view(16)

tensor([-0.4509, -1.1769,  1.1374,  1.2477,  0.2567,  1.1684, -0.4885, -0.1104,
         0.6069, -0.1305, -0.4458,  0.1145,  0.2869,  0.8131,  2.0107, -1.1139])

In [35]:
x.view(2, 8)

tensor([[-0.4509, -1.1769,  1.1374,  1.2477,  0.2567,  1.1684, -0.4885, -0.1104],
        [ 0.6069, -0.1305, -0.4458,  0.1145,  0.2869,  0.8131,  2.0107, -1.1139]])

In [40]:
x.view(-1, 2) # -1 is inferred from other dimensions, if you want fix one dimension and change other dimension accordingly, use this method.

tensor([[-0.4509, -1.1769],
        [ 1.1374,  1.2477],
        [ 0.2567,  1.1684],
        [-0.4885, -0.1104],
        [ 0.6069, -0.1305],
        [-0.4458,  0.1145],
        [ 0.2869,  0.8131],
        [ 2.0107, -1.1139]])

In [42]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.4302])
-1.4301811456680298


### Numpy bridge
* pytorch tensor can be easily changed to numpy array

In [43]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [44]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [45]:
a.add_(1)
print(a)
print(b) # numpy array and torch tensor sharing memory allocation

tensor([2., 2., 2., 2., 2.])
[ 2.  2.  2.  2.  2.]


In [46]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [47]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([-0.4302], device='cuda:0')
tensor([-0.4302], dtype=torch.float64)
