## Autograd

In [10]:
import torch

In [11]:
x = torch.ones(2,2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [12]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [13]:
print(y.grad_fn)

In [14]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [15]:
a = torch.randn(2,2)
a = ((a * 3)/ (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [16]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [17]:
print(y.grad)

None


In [18]:
print(z.grad)

None


In [19]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


* explain above mathematically

$$ o = \frac{1}{4}\sum_{i}{z}_{i} $$
$$ {z}_{i} = 3({x}_{i} + 2 ) ^{2} $$
$$ {z}_{i}({x}_{i} = 1) = 27 $$
$$ \frac{\delta{o}}{\delta{{x}_{i}}} = \frac{3}{2}({x}_{i} + 2) $$
$$ hence, \frac{\delta{o}}{\delta{{x}_{i}}}({x}_{i} = 1) = 4.5$$

In [20]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ -759.2562,    54.6600, -1130.0292], grad_fn=<MulBackward0>)


In [21]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


* explain above mathematically. "y" is not scalar but jacobian matrix can be processed. Thus input "v"-it's gradient vector to calculate- is needed.

$$ {y}_{i} = {x}_{i} \times 2^{10}  $$, in above case
$$ \frac{\delta{y}_{i}}{\delta{{x}_{i}}} = 1024 $$
$$ v = (\frac{\delta{l}}{\delta{{y}_{1}}} \cdots \frac{\delta{l}}{\delta{{y}_{m}}}) $$
$$ J^{T} \cdot v = [1024] \times [0.1, 1.0, 0.0001] $$
J means jacobian matrix for y versus x

In [22]:
x

tensor([-0.3707,  0.0267, -0.5518], requires_grad=True)

In [30]:
x*2**10

tensor([[1024., 1024.],
        [1024., 1024.]], grad_fn=<MulBackward0>)

## applying jacobian matrix to first case.

In [26]:
x = torch.ones(2,2, requires_grad = True)
y = x + 2
z = y * y * 3

In [27]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [28]:
v = torch.tensor([[1.0, 1.0], [10.0, 10.0]], dtype = torch.float)
z.backward(v)

In [29]:
print(x.grad)

tensor([[ 18.,  18.],
        [180., 180.]])
