## Autograd

In [1]:
import torch

In [3]:
x = torch.ones(2,2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
print(y.grad_fn)

In [6]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [9]:
a = torch.randn(2,2)
a = ((a * 3)/ (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [10]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
print(y.grad)

None


In [16]:
print(z.grad)

None


In [17]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


* explain above mathematically

$$ o = \frac{1}{4}\sum_{i}{z}_{i} $$
$$ {z}_{i} = 3({x}_{i} + 2 ) ^{2} $$
$$ {z}_{i}({x}_{i} = 1) = 27 $$
$$ \frac{\delta{o}}{\delta{{x}_{i}}} = \frac{3}{2}({x}_{i} + 2) $$
$$ hence, \frac{\delta{o}}{\delta{{x}_{i}}}({x}_{i} = 1) = 4.5$$

In [19]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ -540.5577, -1255.0487,    17.3635], grad_fn=<MulBackward0>)


In [20]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


* explain above mathematically. "y" is not scalar but jacobian matrix can be processed. Thus input "v"-it's gradient vector to calculate- is needed.

$$ {y}_{i} = {x}_{i} \times 2^{10}  $$, in above case
$$ \frac{\delta{y}_{i}}{\delta{{x}_{i}}} = 1024 $$
$$ v = (\frac{\delta{l}}{\delta{{y}_{1}}} \cdots \frac{\delta{l}}{\delta{{y}_{m}}}) $$
$$ J^{T} \cdot v = [1024] \times [0.1, 1.0, 0.0001] $$
J means jacobian matrix for y versus x

In [34]:
x

tensor([-0.5279, -1.2256,  0.0170], requires_grad=True)

In [35]:
x*2**10

tensor([ -540.5577, -1255.0487,    17.3635], grad_fn=<MulBackward0>)