# Chapter 3. 텐서구조체
## 3.4 이름이 있는 텐서
* https://github.com/deep-learning-with-pytorch/dlwpt-code/blob/master/p1ch3/2_named_tensors.ipynb

In [1]:
import torch
_ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])

/tmp/ipykernel_226815/1646494204.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1408.)
  _ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])


In [2]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [3]:
img_t[0] # by this, you can print out 5x5 image of 0th channel.

tensor([[ 0.7383,  1.9188, -0.2760, -0.2143,  1.8746],
        [-0.8046, -0.7873, -1.2865, -1.1809,  0.1765],
        [-1.3356,  1.9046,  2.0137,  0.4127,  0.4568],
        [ 0.2562, -1.2760,  1.9799, -1.8147,  2.0187],
        [-0.1531,  2.2671,  1.2157,  1.0379, -0.3470]])

In [4]:
img_t[0:] # print out all tensor

tensor([[[ 0.7383,  1.9188, -0.2760, -0.2143,  1.8746],
         [-0.8046, -0.7873, -1.2865, -1.1809,  0.1765],
         [-1.3356,  1.9046,  2.0137,  0.4127,  0.4568],
         [ 0.2562, -1.2760,  1.9799, -1.8147,  2.0187],
         [-0.1531,  2.2671,  1.2157,  1.0379, -0.3470]],

        [[ 0.0618, -0.2955,  0.1364,  0.3346,  0.2909],
         [ 0.6658,  0.0674, -0.8405, -2.3237,  1.2399],
         [-1.0121, -0.5547,  0.5389, -2.8539, -2.3026],
         [ 0.3248,  1.2078, -0.8312, -0.2602,  1.5023],
         [-0.9522,  1.7975, -0.2441,  0.0856,  0.6456]],

        [[-0.0656,  0.2458,  0.0124, -0.0262,  1.2666],
         [ 0.1017, -0.5298,  0.6226,  0.5870,  0.3674],
         [ 0.5646,  1.2552,  0.5984, -0.6512,  0.3381],
         [-0.6264, -0.0401, -0.6419, -0.7837,  0.1894],
         [ 0.1878, -0.4564, -0.2905,  1.3058, -1.4142]]])

In [5]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [6]:
batch_t[0] # first dim of tensor is batch, thus by this you print out first image data with 3x5x5.

tensor([[[ 5.2818e-01, -6.2737e-01, -1.1961e+00,  5.3530e-01, -1.0213e+00],
         [-1.7466e+00,  1.4068e+00, -1.9954e-01,  6.1419e-01, -7.8994e-01],
         [-4.4506e-01,  6.1148e-01,  3.8056e-01,  1.7084e-01,  9.1795e-03],
         [ 3.0943e-01, -1.6437e+00,  9.4434e-01,  3.8656e-02,  5.0007e-01],
         [ 5.8637e-01,  1.1931e-01,  2.0387e-01,  1.6190e+00,  1.5756e-01]],

        [[-1.6395e+00, -1.8684e+00,  1.0098e+00,  1.6866e+00,  3.5682e-01],
         [-1.5056e+00, -1.8162e+00,  8.7935e-01,  1.9987e+00,  2.4348e+00],
         [ 3.1926e-01,  7.4567e-01, -3.4235e-01, -4.7339e-01, -4.4813e-02],
         [ 4.8869e-02, -9.8366e-01, -5.3018e-02, -1.8790e-03,  6.4851e-02],
         [-2.8480e-01, -5.7439e-01, -6.2209e-01,  2.6701e-02,  8.7711e-02]],

        [[ 1.8136e+00, -1.6606e-01, -1.9662e+00, -3.9675e-01,  1.1401e-01],
         [ 2.8895e-01, -3.4719e-01, -1.0204e+00, -8.4504e-01,  6.7931e-01],
         [-1.0789e-01,  5.0379e-01,  9.7689e-01,  1.8768e+00,  1.0116e+00],
        

In [7]:
img_t[None].size() # if you add [none], you add one dim at 0th. 
# imagine you wrap whole data with one dimension of tensor again. 

torch.Size([1, 3, 5, 5])

In [8]:
img_gray_naive = img_t.mean(-3) # mean through channel dimenstion, thus disappear channel
batch_gray_naive = batch_t.mean(-3) # mean through channel dimenstion, thus disappear channel
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [9]:
print(weights)
weights.size()

tensor([0.2126, 0.7152, 0.0722])


torch.Size([3])

In [10]:
print(weights.unsqueeze(0))
weights.unsqueeze(0).size() # unsqueeze(0) is equivalent to [none]


tensor([[0.2126, 0.7152, 0.0722]])


torch.Size([1, 3])

In [11]:
print(weights.unsqueeze(-1))
weights.unsqueeze(-1).size() # unsqueeze(-1) add dimension with one length at last dim.

tensor([[0.2126],
        [0.7152],
        [0.0722]])


torch.Size([3, 1])

In [12]:
weights.size() # but unsqueeze method do not change original tensor, but unsqueeze_ do that.

torch.Size([3])

In [13]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1) 
# original code use unsqueeze_ but it doesn't affect because wegiths.unsqueezed(-1) is temp tensor.
# thus weights.unsqueeze(-1).unsqueeze_(-1) do no effect to original tensor. 
# if you want change original tensor write in weights.unsqueeze_(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)

In [14]:
img_weights.size(), img_t.size(), unsqueezed_weights.size()
# img_weights = (img_t * unsqueezed_weights) dose broadcast. 
# 3x1x1 tensor stech out to 3x5x5 and pointwise multiplication. 

(torch.Size([3, 5, 5]), torch.Size([3, 5, 5]), torch.Size([3, 1, 1]))

In [15]:
batch_weights.shape, batch_t.shape # this calculation was pivoted channel dimension, it has same length.
# rest dimension was , I think, broadcasted.

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]))

In [16]:
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3) # sum through changel dimension
img_gray_weighted.size(), batch_gray_weighted.size()

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [17]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
# above code is equivalent with unsqueezing weights and broadcast, 
# einsum method give name to each dimenstion of tensor, '...' means broadcast

In [18]:
img_gray_weighted_fancy 

tensor([[ 0.1964,  0.2143,  0.0398,  0.1918,  0.6980],
        [ 0.3125, -0.1575, -0.8297, -1.8706,  0.9508],
        [-0.9671,  0.0988,  0.8568, -2.0003, -1.5253],
        [ 0.2416,  0.5896, -0.2199, -0.6285,  1.5173],
        [-0.7000,  1.7346,  0.0629,  0.3762,  0.2858]])

In [19]:
img_gray_weighted

tensor([[ 0.1964,  0.2143,  0.0398,  0.1918,  0.6980],
        [ 0.3125, -0.1575, -0.8297, -1.8706,  0.9508],
        [-0.9671,  0.0988,  0.8568, -2.0003, -1.5253],
        [ 0.2416,  0.5896, -0.2199, -0.6285,  1.5173],
        [-0.7000,  1.7346,  0.0629,  0.3762,  0.2858]])

In [20]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [21]:
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns') # you can redefine name of tensor's dim
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns') # "..." mean ignoring preceded dim
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [22]:
weights_aligned = weights_named.align_as(img_named) # align_as method give same
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

* 텐서끼리 연산 할 때는 차원의 크기가 같은지, 아니면 적어도 브로드캐스팅 될 수 있는 확인해야 한다. 
* 만약 이름이 지정되어 있지만, pytorch가 체크한다. aling_as는 빠진 차원을 채워준다.
* 위 코드에서 weights_named는 channel이라는 dimension만 가진 1차원 tensor였는데, align_as로 채워졌다. 
* 즉 차원을 비교하며 unsqueeze를 할 필요없다는 것이다. 

In [23]:
gray_named = (img_named * weights_aligned).sum('channels') # arg can be the name of dimension
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [24]:
try:
    gray_named = (img_named[..., :3] * weights_named).sum('channels')
except Exception as e:
    print(e)

Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.


In [25]:
# you can remove the name of dimensions
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

* 이 책에서는 앞으로 텐서 이름을 지정하지 않는다고함. (왜?)

## 3.5 dtype 관련 

In [26]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short) # short dtype is signed integer
points_64 * points_short  # works from PyTorch 1.3 onwards


tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## 3.6 텐서 API

In [27]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [28]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1) # equivalent with above cell

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [29]:
a = torch.ones(3, 2)
a_t = a.t() # only work with 2D tensor

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## 3.7 텐서 저장소(storage)관점에서 보기, 3.8 텐서 메타데이터: 사이즈, 오프셋, 스트라이드
* 이건 ../DL_torch_book/Ch01_intro.ipynb 내용과 겹쳐 생략.

In [30]:
# 3.8.3 transpose of high dimesion tensor
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2) # swith(transpose) 0index dim and 2index dim
some_t.shape, transpose_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [31]:
some_t.stride(), transpose_t.stride() # dimenstion with stride 1 = contigouos tensor
# it is effectively approach memory in point of view of data locality.

((20, 5, 1), (1, 5, 20))

In [32]:
some_t.is_contiguous()

True

In [33]:
transpose_t.is_contiguous()

False

In [34]:
transpose_t_con = transpose_t.contiguous() # to make this tensor as coniguous
# it change form of storage()
transpose_t_con.shape, transpose_t_con.stride()

(torch.Size([5, 4, 3]), (12, 3, 1))

## 3.9 텐서를 GPU에서


In [44]:
# using device argument
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device=device)

In [46]:
points_gpu.device

device(type='cuda', index=0)

In [48]:
points_64_gpu = points_64.to(device=device)
points_64.device, points_64_gpu.device

(device(type='cpu'), device(type='cuda', index=0))

In [52]:
points_64 = 2 * points_64 # calculated on CPU
points_64_gpu = 2 * points_64.to(device=device) # calculated on GPU
points_64_gpu.device # and remain the result in GPU

device(type='cuda', index=0)

In [54]:
points_64_gpu = points_64.cuda(0) #another method, int arg can set the specific GPU
points_64_gpu.device

device(type='cuda', index=0)

In [55]:
point_64_cpu = points_64_gpu.cpu()
point_64_cpu.device

device(type='cpu')

In [59]:
points_64_gpu = points_64.to(device=device, dtype=torch.short) # move the data and simultaneously change to dtype
points_64_gpu.device, points_64_gpu.dtype, points_64.dtype

(device(type='cuda', index=0), torch.int16, torch.float64)

## 3.10 numpy 호환

In [61]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np # note that dtype is float32, contrast to that default dtype of numpy is float64.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [64]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [69]:
points_gpu = points.cuda()
#points_np = points_gpu.numpy() # directly convert to numpy is not working, if tensor is on GPU
# you have to move the tensor back to cpu to convert to numpy
points_cpu = points_gpu.cpu()
points_np = points_cpu.numpy()
points_np


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

# 3.12 텐서 직렬화, 저장, 호환되는 형식으로 저장 

In [71]:
with open('./data/ch03/ourpoints.t', 'wb') as f:
    torch.save(points, f) # torch use pickle in backend

In [73]:
with open('./data/ch03/ourpoints.t', 'rb') as f:
    points_loaded= torch.load(f)
points_loaded
# but this type is only working for pytorch

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [74]:
import h5py

f = h5py.File('./data/ch03/ourpoints.hdf5', 'w')
dset = f.create_dataset('coord', data=points.numpy())
f.close()

In [78]:
# hdf5 do not have to open whole data on the disk, it can directly index data on the disk
f = h5py.File('./data/ch03/ourpoints.hdf5', 'r')
dset = f['coord']
last_points = dset[-2:]
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [79]:
last_points = torch.from_numpy(dset[-2:])
f.close()
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [88]:
# if closed, you cann't approach to dset object
try:
    dset[-2:]
except:
    print(" you cann't approach to dset object after f.close()")

 you cann't approach to dset object after f.close()


In [89]:
with h5py.File('./data/ch03/ourpoints.hdf5', 'r') as f: #equivalent with open()
    dset = f['coord']
    last_points = dset[-2:]
print(last_points)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 3.14 연습문제


In [97]:
# 1
ex1 = list(range(9))
ex1_tensor = torch.tensor(ex1)
ex1_tensor.size(), ex1_tensor.stride(), ex1_tensor.storage_offset()

(torch.Size([9]), (1,), 0)

In [106]:
# 1.a
#print(a)
b = a.view(2,3)
a_t = a.t()
a, b, a_t

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [108]:
a.stride(), b.stride(), a_t.stride() # view act like tranpose + contigous.

((2, 1), (3, 1), (1, 2))

In [112]:
# 1.c
c = b[1:,1:]
c.size(), c.storage_offset(), c.stride(), c # sub_tensor maintain same stride with original tensor

(torch.Size([1, 2]), 4, (3, 1), tensor([[1., 1.]]))

In [124]:
a =torch.rand(2,2)
a

tensor([[0.4269, 0.4678],
        [0.0624, 0.6665]])