# Chapter 3. 텐서구조체
## 3.4 이름이 있는 텐서
* https://github.com/deep-learning-with-pytorch/dlwpt-code/blob/master/p1ch3/2_named_tensors.ipynb

In [131]:
import torch
_ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])

In [132]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [133]:
img_t[0] # by this, you can print out 5x5 image of 0th channel.

tensor([[ 0.3126, -0.5272, -1.0891, -0.9436,  1.3990],
        [ 0.6383,  0.7600,  1.0159,  0.1689, -1.2332],
        [ 0.5743,  1.6920,  1.4063,  1.0888,  1.2737],
        [ 0.6946,  0.3385, -0.7794, -1.3830,  1.5432],
        [ 0.1189,  1.2276,  1.8664,  1.0562, -0.1446]])

In [134]:
img_t[0:] # print out all tensor

tensor([[[ 0.3126, -0.5272, -1.0891, -0.9436,  1.3990],
         [ 0.6383,  0.7600,  1.0159,  0.1689, -1.2332],
         [ 0.5743,  1.6920,  1.4063,  1.0888,  1.2737],
         [ 0.6946,  0.3385, -0.7794, -1.3830,  1.5432],
         [ 0.1189,  1.2276,  1.8664,  1.0562, -0.1446]],

        [[ 0.8139,  0.4725,  2.1944,  0.1213, -0.1462],
         [-0.3711,  1.2576,  0.1531, -1.3440,  0.4629],
         [-1.0107,  0.4668, -0.0521, -0.2063,  0.2032],
         [-0.1380, -1.4370,  0.6503, -0.9988, -0.6896],
         [-0.1973,  0.2925, -0.1569, -0.7541,  0.4995]],

        [[-0.7742, -0.2897,  1.5014, -1.0714,  1.5222],
         [-1.3452,  0.6464,  0.0677, -0.7798, -0.0619],
         [-0.9003,  0.4632,  0.9690,  0.1639, -0.4950],
         [ 1.1165,  0.8820,  0.0460,  0.1322, -0.0371],
         [ 1.3960,  0.6710,  1.2203,  0.1145,  0.5692]]])

In [135]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [136]:
batch_t[0] # first dim of tensor is batch, thus by this you print out first image data with 3x5x5.

tensor([[[-1.2091,  0.1995, -0.7416,  0.1909, -0.4584],
         [ 1.7072, -0.5648, -0.7092,  0.3115,  0.6508],
         [ 0.8624,  1.2366,  2.0773, -1.2187,  0.5553],
         [ 1.1659, -2.5488,  0.6690, -0.9867, -0.2997],
         [-1.5916,  0.5156,  0.5894, -0.8936, -0.3151]],

        [[ 0.4081,  0.6684, -1.3292,  0.1385, -0.9094],
         [ 0.0332,  0.6434, -0.3412, -0.7759, -1.0176],
         [ 2.5028, -0.4970, -1.0738,  0.7211, -0.7651],
         [-0.6766,  2.1116, -0.2088, -0.6841,  0.2709],
         [ 0.0701, -0.8069,  0.0925,  0.3426,  2.0478]],

        [[-2.0998, -0.2465,  0.7039, -0.1692, -0.2314],
         [-0.0746,  1.0015, -0.3049, -1.4522, -1.3886],
         [-0.6563,  0.9668,  0.8859,  3.1799, -0.5477],
         [ 0.6126,  0.1032, -1.0765, -1.1260, -0.5255],
         [-0.0160, -2.4074,  0.7244,  0.6569, -0.2978]]])

In [137]:
img_t[None].size() # if you add [none], you add one dim at 0th. 
# imagine you wrap whole data with one dimension of tensor again. 

torch.Size([1, 3, 5, 5])

In [138]:
img_gray_naive = img_t.mean(-3) # mean through channel dimenstion, thus disappear channel
batch_gray_naive = batch_t.mean(-3) # mean through channel dimenstion, thus disappear channel
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [139]:
print(weights)
weights.size()

tensor([0.2126, 0.7152, 0.0722])


torch.Size([3])

In [140]:
print(weights.unsqueeze(0))
weights.unsqueeze(0).size() # unsqueeze(0) is equivalent to [none]


tensor([[0.2126, 0.7152, 0.0722]])


torch.Size([1, 3])

In [141]:
print(weights.unsqueeze(-1))
weights.unsqueeze(-1).size() # unsqueeze(-1) add dimension with one length at last dim.

tensor([[0.2126],
        [0.7152],
        [0.0722]])


torch.Size([3, 1])

In [142]:
weights.size() # but unsqueeze method do not change original tensor, but unsqueeze_ do that.

torch.Size([3])

In [146]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1) 
# original code use unsqueeze_ but it doesn't affect because wegiths.unsqueezed(-1) is temp tensor.
# thus weights.unsqueeze(-1).unsqueeze_(-1) do no effect to original tensor. 
# if you want change original tensor write in weights.unsqueeze_(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)

In [159]:
img_weights.size(), img_t.size(), unsqueezed_weights.size()
# img_weights = (img_t * unsqueezed_weights) dose broadcast. 
# 3x1x1 tensor stech out to 3x5x5 and pointwise multiplication. 

(torch.Size([3, 5, 5]), torch.Size([3, 5, 5]), torch.Size([3, 1, 1]))

In [160]:
batch_weights.shape, batch_t.shape # this calculation was pivoted channel dimension, it has same length.
# rest dimension was , I think, broadcasted.

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]))

In [152]:
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3) # sum through changel dimension
img_gray_weighted.size(), batch_gray_weighted.size()

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [153]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
# above code is equivalent with unsqueezing weights and broadcast, 
# einsum method give name to each dimenstion of tensor, '...' means broadcast

In [154]:
img_gray_weighted_fancy 

tensor([[ 0.5927,  0.2049,  1.4463, -0.1912,  0.3028],
        [-0.2269,  1.1077,  0.3303, -0.9817,  0.0644],
        [-0.6657,  0.7270,  0.3317,  0.0958,  0.3804],
        [ 0.1296, -0.8921,  0.3027, -0.9988, -0.1678],
        [-0.0150,  0.5186,  0.3727, -0.3065,  0.3676]])

In [155]:
img_gray_weighted

tensor([[ 0.5927,  0.2049,  1.4463, -0.1912,  0.3028],
        [-0.2269,  1.1077,  0.3303, -0.9817,  0.0644],
        [-0.6657,  0.7270,  0.3317,  0.0958,  0.3804],
        [ 0.1296, -0.8921,  0.3027, -0.9988, -0.1678],
        [-0.0150,  0.5186,  0.3727, -0.3065,  0.3676]])

In [156]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [157]:
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns') # you can redefine name of tensor's dim
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns') # "..." mean ignoring preceded dim
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [158]:
weights_aligned = weights_named.align_as(img_named) # align_as method give same
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

* 텐서끼리 연산 할 때는 차원의 크기가 같은지, 아니면 적어도 브로드캐스팅 될 수 있는 확인해야 한다. 
* 만약 이름이 지정되어 있지만, pytorch가 체크한다. aling_as는 빠진 차원을 채워준다.
* 위 코드에서 weights_named는 channel이라는 dimension만 가진 1차원 tensor였는데, align_as로 채워졌다. 
* 즉 차원을 비교하며 unsqueeze를 할 필요없다는 것이다. 

In [161]:
gray_named = (img_named * weights_aligned).sum('channels') # arg can be the name of dimension
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [162]:
try:
    gray_named = (img_named[..., :3] * weights_named).sum('channels')
except Exception as e:
    print(e)

Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.


In [166]:
# you can remove the name of dimensions
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

* 이 책에서는 앞으로 텐서 이름을 지정하지 않는다고함. (왜?)

## 3.5 dtype 관련 

In [167]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short) # short dtype is signed integer
points_64 * points_short  # works from PyTorch 1.3 onwards


tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## 3.6 텐서 API

In [170]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [172]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1) # equivalent with above cell

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [174]:
a = torch.ones(3, 2)
a_t = a.t() # only work with 2D tensor

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## 3.7 텐서 저장소(storage)관점에서 보기, 3.8 텐서 메타데이터: 사이즈, 오프셋, 스트라이드
* 이건 ../DL_torch_book/Ch01_intro.ipynb 내용과 겹쳐 생략.

In [177]:
# 3.8.3 transpose of high dimesion tensor
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2) # swith(transpose) 0index dim and 2index dim
some_t.shape, transpose_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [179]:
some_t.stride(), transpose_t.stride() # dimenstion with stride 1 = contigouos tensor
# it is effectively approach memory in point of view of data locality.

((20, 5, 1), (1, 5, 20))

In [180]:
some_t.is_contiguous()

True

In [181]:
transpose_t.is_contiguous()

False

In [186]:
transpose_t_con = transpose_t.contiguous() # to make this tensor as coniguous
# it change form of storage()
transpose_t_con.shape, transpose_t_con.stride()

(torch.Size([5, 4, 3]), (12, 3, 1))